### ISSUE TITLE
support launching steam as steam-native

### ISSUE THREAD

**Issue by ca1f** [coldfix/steam-acolyte#19]
from the looks of it, steam-acolyte launches steam on linux always as `/usr/bin/steam` and has no option for launching steam as `/usr/bin/steam-native`.

I could provide a PR for this functionality but I'm not exactly sure what would be the desired way to switch between these two methods of launching steam so I would like to use this ticket to discuss whenever A) it's desired to provide a way to switch between these two methods of launching steam and B) how to implement it.

**Comment by coldfix** [comment]
Hey, you can currently use `steam-acolyte --exe steam-native`, but I want to improve support in the future so that it can be configured in a config file (and possibly even controlled using the GUI).

**Comment by coldfix** [comment]
If you have any conceptions on how a UI to set the desired executable should look like, please bring them forth.

**Comment by coldfix** [comment]
(This should also be better documented and made easier see #24).
