### ISSUE TITLE
login lost after steamname change

### ISSUE THREAD

**Issue by serossi** [coldfix/steam-acolyte#20]
Not shure if this is an acolyte issue or some steam special shenanigan
if the displayname is changed on another pc i need to enter password and then auth token again in acolyte

ive only found acolytes directory with those vdf files. if thats the only thing acolyte stores then i think its an issue with steam itself
resetting all tokens

anybody can confirm ?

**Comment by coldfix** [comment]
Can you check whether the same happens if you start steam normally without acolyte?

**Comment by serossi** [comment]
ok nvm, i cannot reproduce it now anymore. my best guess its steam, maybe in combination of an update at the same time.

now name changes work with and without acolyte running in any condition via a second pc. 
at least we know now that acolyte is resistent to such cases :)

**Comment by coldfix** [comment]
Ok, I'll close in that case.
