### ISSUE TITLE
support flatpak steam

### ISSUE THREAD

**Issue by tazihad** [coldfix/steam-acolyte#23]
I have flatpak version of steam installed. I get this error.
```
$ steam-acolyte
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Unable to find steam user path!
```

**Comment by coldfix** [comment]
Might be resolved in f08f8571587d2cc6e245c92660c4c27926238639. Let me know if you have any problems. See #18 and #24.
