### ISSUE TITLE
Steam login expiring

### ISSUE THREAD

**Issue by tuxtergames** [coldfix/steam-acolyte#29]
Just a curiosit, Login saved on acolyte expire if not using for a few time?

If its happen is it possible backup then for the future, I use some share games here, tks!!!!

**Comment by coldfix** [comment]
Hey,

yes, logins will expire after some time if unused. Nothing I can really do about this, this is how steam handles it. The only way to somewhat change this would be to save passwords on the acolyte side - which I don't want to do, and which would mean you would still have to enter 2FA. See also README about this.

Best, Thomas

**Comment by tuxtergames** [comment]
> Hey,
> 
> yes, logins will expire after some time if unused. Nothing I can really do about this, this is how steam handles it. The only way to somewhat change this would be to save passwords on the acolyte side - which I don't want to do, and which would mean you would still have to enter 2FA. See also README about this.
> 
> Best, Thomas

tks for reply!!!!
