### ISSUE TITLE
Fails to start with Python 3.11 (No module named 'vdf')

### ISSUE THREAD

**Issue by Razzaline** [coldfix/steam-acolyte#30]
Ever since a Python update a little while ago, Steam Acolyte and a few other programs relying on Python have failed to start. Here is the terminal output:

`Traceback (most recent call last):
  File "/usr/bin/steam-acolyte", line 33, in <module>
    sys.exit(load_entry_point('steam-acolyte==0.9.0', 'console_scripts', 'steam-acolyte')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/steam-acolyte", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/steam_acolyte/app.py", line 32, in <module>
    from steam_acolyte.steam import Steam
  File "/usr/lib/python3.11/site-packages/steam_acolyte/steam.py", line 4, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
`

I am running Manjaro on kernel 6.3, and Python 3 and Pip are both installed through system packages. I'm using the latest version of Steam Acolyte, version 0.9.0, and Steam is installed both through the package manager and Flatpak.

**Comment by coldfix** [comment]
It looks like you installed those applications with one version of python then updated to a newer version of python. This means the previously installed applications are now broken (all needed code is installed for a different python version).

I recommend to fully remove and then reinstall all affected applications. You will most likely have to do this by hand, i.e. `rm -rf /usr/lib/python3.10/site-packages/XXX` and manually delete executables from `/usr/bin`.

For future, I will advise not to use pip as root to save you the trouble of manually deleting these files from your system root on the next python update. Prefer a plain `pip install` without sudo. In that case you will still have to remove old apps manually when upgrading python, but just from your home directory, not from your system root, or even use a tool like [pipx](https://pypa.github.io/pipx/) for better encapsulation.

Best solution would be to use a system package of course.

**Comment by Razzaline** [comment]
Okay, it looks like all of these were actually installed as system packages but didn't get updated along with Python, so they were still in the 3.10 site-packages directory. So it wasn't a matter of using Pip as root.

**Comment by coldfix** [comment]
Ok. So your problem is solved? I find it a bit unexpected that some python packages aren't updated when python is updated in manjaro? Unless these were AUR packages, in that case it makes sense -> the solution would be to uninstall and reinstall.

**Comment by Razzaline** [comment]
Oh, these were all AUR packages, yes. Some of them were built packages from repositories that build from AUR, like chaotic-aur, but as far as I know they all originated with the AUR, and many have not been touched for a while, so that might be why >.<
