### ISSUE TITLE
update to python 3.12  broke Steam Acolyte

### ISSUE THREAD

**Issue by narayanls** [coldfix/steam-acolyte#33]
Hi there! I really enjoy steam acolyte due to unlimited accounts that I can connect to. At this moment I use 13 accounts.
But today my Linux system (BigLinux, a Linux distro based in Manjaro) receive a large update and python was updated to 3.12. Now I can't open Steam Acolyte, this is the error that I read when I try to open it in terminal:

Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/steam-acolyte", line 33, in <module>
    sys.exit(load_entry_point('steam-acolyte==0.9.0', 'console_scripts', 'steam-acolyte')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sbin/steam-acolyte", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for steam-acolyte

**Comment by coldfix** [comment]
Hi,

thank you, it's great to hear that this package is useful to you. My first guess would be that you didn't reinstall acolyte after the python update. An existing installation of a python package can not easily be migrated to a newer python version without a fresh install. Does that help?

Best, Thomas

**Comment by narayanls** [comment]
That works! thank you so much.
