### ISSUE TITLE
No side bar or adjustment when login multiple accounts - also tray icon in gnome not working

### ISSUE THREAD

**Issue by narayanls** [coldfix/steam-acolyte#34]
Hello, I noticed that steam acolyte doesn't have a side bar or auto window adjustment when login  multiple accounts. So there's a point if I login more accounts they gone be "swallow" by the screen. I saw this happen in xfce and now this is about to happen in gnome (I have more 3 accounts to login). The different is that xfce tray icon allows me to connect in my multiple accounts and to login in a new one. In gnome tray icon appears but does nothing.
Here's a video to crarify:

https://github.com/user-attachments/assets/cc49c57e-066c-4a79-94a8-0137d32ee651

Here's my system info:
![Captura de tela de 2024-08-01 08-39-34](https://github.com/user-attachments/assets/69d927de-db3f-478d-a23e-e386696ec4da)
Python 3.12.4

**Comment by narayanls** [comment]
Hi again! Talking to a programmer friend, he found out a solution: he creates a patch that split the screen every 15 accounts.
Here's the patch and the command to use it:
[fix-resize.zip](https://github.com/user-attachments/files/16458110/fix-resize.zip)
open terminal in the folder where patch is and then use the following command:
`sudo patch /usr/lib/python3.12/site-packages/steam_acolyte/window.py < fix-resize.patch`

Here's the result:
![Captura de tela de 2024-08-01 11-35-27](https://github.com/user-attachments/assets/72188e25-85da-4d11-8867-4b7aeee0e70f)

**Comment by coldfix** [comment]
Another option could be to use a QScrollArea.

**Comment by narayanls** [comment]
Hi, he made another change using QScrollArea and Resize, now it's perfect:

https://github.com/user-attachments/assets/087b41d2-f8da-44d1-af32-f6c9c278fc5b

He made the alterations in window.py:
[window.zip](https://github.com/user-attachments/files/16481155/window.zip)

**Comment by coldfix** [comment]
Thanks for your contribution. I integrated a similar patch.
